# Generated by Django 5.2.17 on 2026-10-01 01:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("manager", "Manager"), ("member", "Member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tracker.team")),
            ],
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("content_hash", models.CharField(max_length=64)),
                ("payload", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("retrying", "Retrying"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(null=True)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tracker.membership"),
                ),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tracker.team")),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=40)),
                ("object_id", models.CharField(max_length=64)),
                ("changes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tracker.team")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=10000)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("in_progress", "In Progress"), ("done", "Done")],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_requests",
                        to="tracker.membership",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_requests",
                        to="tracker.membership",
                    ),
                ),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tracker.team")),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(fields=("team", "user"), name="one_membership_per_team"),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(fields=("id", "team"), name="membership_id_team"),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["owner", "manager", "member"])), name="valid_membership_role"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["status", "next_attempt_at"], name="tracker_imp_status_b1c74e_idx"),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.UniqueConstraint(fields=("team", "idempotency_key"), name="unique_import_key"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["team", "-created_at"], name="tracker_aud_team_id_9351cb_idx"),
        ),
        migrations.AddIndex(
            model_name="workrequest",
            index=models.Index(fields=["team", "status", "-created_at"], name="tracker_wor_team_id_c7e630_idx"),
        ),
        migrations.AddConstraint(
            model_name="workrequest",
            constraint=models.UniqueConstraint(fields=("team", "external_id"), name="unique_external_request"),
        ),
        migrations.AddConstraint(
            model_name="workrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "in_progress", "done"])), name="valid_request_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="workrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", ["low", "normal", "high"])), name="valid_request_priority"
            ),
        ),
    ]
